### ISSUE TITLE
Some more links

### ISSUE THREAD

**Issue by AndreyGurevich** [beamandrew/medical-data#32]
May be it will be useful:
* https://archive.ics.uci.edu/ml/datasets.html?format=&task=&att=&area=life&numAtt=&numIns=&type=&sort=nameUp&view=table

* http://www.ebusinessgems.com/blog/socio-economic-database/database-diseases-disorders-illnesses/

* http://disease-ontology.org/downloads/

* https://www.kaggle.com/plarmuseau/sdsort

**Comment by bwallace** [comment]
also potentially of interest: our EBM-NLP corpus (annotated articles describing RCTs of interventions) -- [http://www.ebm-nlp.com/](http://www.ebm-nlp.com/ )

**Comment by beamandrew** [comment]
I'd love to include it if you submit it as a PR.
