### ISSUE TITLE
DREAM challenges

### ISSUE THREAD

**Issue by kevin-keraudren** [beamandrew/medical-data#4]
It could be worth mentionning the dream Challenges on this page, either as a single entry for all of them, or an entry per challenge.

http://dreamchallenges.org/

In particular:

**The Digital Mammography DREAM Challenge.**
June 29, 2016- Feb. 20, 2017 (open)
With generous support from the Laura and John Arnold Foundation this $1.2 million Challenge, one of two large prize Coding4Cancer Challenges, seeks to improve the accuracy of breast cancer detection and reduce the current rate of patient callbacks.

**Comment by skrish13** [comment]
Thanks, good suggestion! DREAM challenge is been added now.

**Comment by beamandrew** [comment]
This has been added, closing now
