### ISSUE TITLE
Add dataset for LOINC embeddings?

### ISSUE THREAD

**Issue by elleros** [beamandrew/medical-data#41]
Hi,

I shared a set of Word2Vec embeddings of LOINC codes via GitHub. I trained them from lab orders at my organization (City of Hope National Medical Center). I wonder if you could include it in your list. The markdown with description and related links is below. 

Thank you!
Lorenzo

***
__Evaluation of Embeddings of Laboratory Test Codes for Patients at a Cancer Center__  
200 dimensional Word2Vec embeddings of 1098 laboratory test codes (LOINCs) trained from 8,280,238 lab orders for 79,081 patients at City of Hope National Medical Center
Paper: https://arxiv.org/abs/1907.09600
Data: https://github.com/elleros/DSHealth2019_loinc_embeddings

**Comment by beamandrew** [comment]
If you submit this as a PR I'll approve and merge
