### ISSUE TITLE
Cell counting dataset

### ISSUE THREAD

**Issue by mrgloom** [beamandrew/medical-data#6]
Are there any cell counting dataset available?

**Comment by skrish13** [comment]
Check [grand-challenges](https://grand-challenge.org/All_Challenges/). I think you should be able to find something related. They have really huge amount of challenges and conferences (associated with challenges) in various fields and topics.

**Comment by mrgloom** [comment]
At least I found this:
http://academictorrents.com/details/b32305598175bb8e03c5f350e962d772a910641c
